version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: mysql+pymysql://pieraly:pieraly@host.docker.internal/items_db
    depends_on:
      - db

  db:
    image: mysql
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: pieraly
      MYSQL_DATABASE: items_db
      MYSQL_USER: pieraly
      MYSQL_PASSWORD: pieraly
    ports:
      - "6033:3306"

